// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _de = {
  "Store": "Shop",
  "Settings": "Einstellungen",
  "SelectLanguage": "Sprache auswählen",
  "Help": "Hilfe",
  "HelpText": "Tipps zur Anwendung",
  "HelpDialog": "Mit dieser Anwendung können Sie Ihre To-Do-Liste erstellen, bearbeiten und löschen.\n1 Arbeitsstunde entspricht 1 Kredit.\nWenn Routinetage ausgewählt sind, wird diese Aufgabe als Routine gespeichert. Wenn nicht ausgewählt, wird sie als normale Aufgabe gespeichert.",
  "Exit": "Beenden",
  "Profile": "Profil",
  "Skills": "Fähigkeiten",
  "Skill": "Fähigkeit",
  "Attributes": "Attribute",
  "Attribute": "Attribut",
  "CreateSkill": "Fähigkeit erstellen",
  "CreateAttribute": "Attribut erstellen",
  "WeeklyProgress": "Wöchentlicher Fortschritt",
  "WeeklyWorkHour": "Wöchentliche Arbeitsstunden",
  "Add": "Hinzufügen",
  "Buy": "Kaufen",
  "OnePiece": "{} Stück",
  "Create": "Erstellen",
  "Name": "Name",
  "Cancel": "Abbrechen",
  "TraitNameEmpty": "Der Name des Merkmals darf nicht leer sein.",
  "RoutineStartDateError": "Das Startdatum der Routine darf nicht vor heute liegen.",
  "EditTask": "Aufgabe bearbeiten",
  "EditRoutine": "Routine bearbeiten",
  "Edit": "Bearbeiten",
  "AddTask": "Aufgabe hinzufügen",
  "TaskName": "Aufgabenname",
  "Hour": "Stunde",
  "h": "h",
  "Minute": "Minute",
  "m": "m",
  "Second": "Sekunde",
  "s": "s",
  "Warning": "Warnung",
  "Info": "Info",
  "Success": "Erfolg",
  "NoTaskForToday": "Keine Aufgabe für heute",
  "RoutineForFuture": "Routine kann nicht interagiert werden, da sie in der Zukunft liegt",
  "Delete": "Löschen",
  "Failed": "Fehlgeschlagen",
  "ChangeDate": "Datum ändern",
  "Times": "Mal",
  "AllTime": "Gesamte Zeit",
  "DaysInProgress": "Tage im Gange",
  "AvarageDay": "Durchschnittstag",
  "Routines": "Routinen",
  "FutureRoutines": "Zukünftige Routinen",
  "Completed": "Abgeschlossen",
  "NameEmpty": "Name darf nicht leer sein.",
  "AddItem": "Element hinzufügen",
  "EditItem": "Element bearbeiten",
  "TaskDescription": "Aufgabenbeschreibung",
  "SelectTime": "Zeit auswählen",
  "Average": "Durchschnitt",
  "InADay": "An einem Tag",
  "BestHour": "Beste Stunde",
  "BestDay": "Bester Tag",
  "LongestStreak": "Längste Serie",
  "CurrentStreak": "Aktuelle Serie",
  "Streak": "Serie",
  "Day": "Tag",
  "Today": "Heute",
  "RecentLogs": "Letzte Protokolle",
  "Cancelled": "Abgebrochen",
  "InProgress": "In Bearbeitung",
  "NotStarted": "Nicht begonnen",
  "TotalTime": "Gesamtzeit",
  "Priority": "Priorität",
  "HighPriority": "Hoch",
  "MediumPriority": "Mittel",
  "LowPriority": "Niedrig",
  "CurrentProgress": "Aktueller Fortschritt",
  "Minutes": "Minuten",
  "Count": "Anzahl",
  "Save": "Speichern",
  "DeleteAllData": "Alle Daten löschen",
  "DeleteAllDataWarning": "Möchten Sie wirklich alle Daten löschen?",
  "DeleteAllDataSuccess": "Alle Daten wurden gelöscht",
  "Yes": "Ja",
  "Hide": "Ausblenden",
  "Show": "Anzeigen",
  "storage_permission_required": "Für die Sicherung ist eine Speicherberechtigung erforderlich",
  "storage_access_error": "Konnte nicht auf das Speicherverzeichnis zugreifen",
  "downloads_access_error": "Konnte nicht auf das Download-Verzeichnis zugreifen",
  "backup_created_successfully": "Sicherung erfolgreich im Download-Ordner erstellt",
  "backup_creation_error": "Fehler beim Erstellen der Sicherung: {}",
  "backup_restored_successfully": "Sicherung erfolgreich wiederhergestellt",
  "backup_restore_cancelled": "Wiederherstellung der Sicherung abgebrochen",
  "backup_restore_error": "Fehler bei der Wiederherstellung der Sicherung: {}",
  "task_completed_title": "🎉 {} Abgeschlossen",
  "task_completed_desc": "Gesamtdauer: {}",
  "item_expired_title": "⚠️ {} Zeit abgelaufen",
  "item_expired_desc": "Zeitlimit nicht überschreiten!",
  "notification_permission_required": "Benachrichtigungsberechtigung ist erforderlich",
  "alarm_permission_required": "Alarmberechtigung ist erforderlich",
  "notification_channel_name": "Aufgabenabschluss",
  "notification_channel_desc": "Benachrichtigungen für abgeschlossene Aufgaben",
  "ThemeSelection": "Themenauswahl",
  "ThemeSelectionSubtitle": "Dunkel/Hell-Thema ändern",
  "DataManagement": "Datenverwaltung",
  "DataManagementSubtitle": "Sichern oder Wiederherstellen Ihrer Daten",
  "ExportData": "Daten sichern",
  "ImportData": "Aus Sicherung wiederherstellen",
  "Subtasks": "Unteraufgaben",
  "AddSubtask": "Unteraufgabe hinzufügen",
  "EditSubtask": "Unteraufgabe bearbeiten",
  "SubtaskEmpty": "Unteraufgabe darf nicht leer sein.",
  "HideSubtasks": "Unteraufgaben ausblenden",
  "ShowSubtasks": "Unteraufgaben anzeigen",
  "Location": "Standort",
  "EnterLocation": "Standort eingeben",
  "ShowOnMap": "Auf Karte anzeigen",
  "Title": "Titel",
  "Description": "Beschreibung",
  "EnterTitle": "Titel eingeben",
  "EnterDescription": "Beschreibung eingeben",
  "AddManualLog": "Manuellen Eintrag hinzufügen",
  "NoLogsYet": "Noch keine Einträge",
  "Date": "Datum",
  "Time": "Zeit",
  "Progress": "Fortschritt",
  "EnterCount": "Anzahl eingeben",
  "Hours": "Stunden",
  "CompletedTask": "Abgeschlossene Aufgabe",
  "EditLog": "Eintrag bearbeiten",
  "Status": "Status",
  "Category": "Kategorie",
  "Categories": "Kategorien",
  "CreateCategory": "Kategorie erstellen",
  "EditCategory": "Kategorie bearbeiten",
  "CategoryName": "Kategoriename",
  "CategoryNameEmpty": "Kategoriename darf nicht leer sein.",
  "SelectColor": "Farbe auswählen",
  "NoCategories": "Keine Kategorien verfügbar",
  "NoCategory": "Keine Kategorie",
  "CreateNewCategory": "Neue Kategorie erstellen",
  "DeleteCategory": "Kategorie löschen",
  "DeleteCategoryConfirmation": "Sind Sie sicher, dass Sie diese Kategorie löschen möchten?",
  "NoCategoriesYet": "Noch keine Kategorien",
  "AddCategory": "Kategorie hinzufügen",
  "NoTasksInCategory": "Keine Aufgaben in dieser Kategorie",
  "Tomorrow": "Morgen",
  "Yesterday": "Gestern",
  "AllTasks": "Alle Aufgaben",
  "NoTasksYet": "Noch keine Aufgaben",
  "Tasks": "Aufgaben",
  "Close": "Schließen",
  "ShowCompleted": "Abgeschlossene anzeigen",
  "HideCompleted": "Abgeschlossene ausblenden",
  "SearchTasks": "Aufgaben suchen...",
  "Search": "Suchen",
  "Filters": "Filter",
  "Copy": "Kopieren",
  "CopiedDescription": "Beschreibung in die Zwischenablage kopiert",
  "ContactUs": "Kontaktiere uns",
  "ContactUsSubtitle": "Nehmen Sie Kontakt mit uns auf",
  "PrivacyPolicy": "Datenschutzrichtlinie",
  "PrivacyPolicySubtitle": "Lesen Sie unsere Datenschutzrichtlinie"
};
static const Map<String,dynamic> _en = {
  "Store": "Store",
  "Settings": "Settings",
  "SelectLanguage": "Select Language",
  "Help": "Help",
  "HelpText": "Tips about the application.",
  "HelpDialog": "With this application, you can create, edit, and delete your to-do list.\n1 hour of work equals 1 credit.\nIf routine days are selected, that task is saved as a routine. If not selected, it is saved as a normal task.",
  "Exit": "Exit",
  "Profile": "Profile",
  "Skills": "Skills",
  "Skill": "Skill",
  "Attributes": "Attributes",
  "Attribute": "Attribute",
  "CreateSkill": "Create Skill",
  "CreateAttribute": "Create Attribute",
  "WeeklyProgress": "Weekly Progress",
  "WeeklyWorkHour": "Weekly Work Hour",
  "Add": "Add",
  "Buy": "Buy",
  "OnePiece": "{} Piece",
  "Create": "Create",
  "Name": "Name",
  "Cancel": "Cancel",
  "TraitNameEmpty": "Trait name cannot be empty.",
  "RoutineStartDateError": "Routine start date cannot be before today.",
  "EditTask": "Edit Task",
  "EditRoutine": "Edit Routine",
  "Edit": "Edit",
  "AddTask": "Add Task",
  "TaskName": "Task Name",
  "Hour": "Hour",
  "h": "h",
  "Minute": "Minute",
  "m": "m",
  "Second": "Second",
  "s": "s",
  "Warning": "Warning",
  "Info": "Info",
  "Success": "Success",
  "NoTaskForToday": "No task for today",
  "RoutineForFuture": "Routine cannot be interacted with because it is in the future",
  "Delete": "Delete",
  "Failed": "Failed",
  "ChangeDate": "Change Date",
  "Times": "Times",
  "AllTime": "All Time",
  "DaysInProgress": "days in progress",
  "AvarageDay": "Average day",
  "Routines": "Routines",
  "FutureRoutines": "Future Routines",
  "Completed": "Completed",
  "NameEmpty": "Name cannot be empty.",
  "AddItem": "Add Item",
  "EditItem": "Edit Item",
  "TaskDescription": "Task Description",
  "SelectTime": "Select Time",
  "Average": "Average",
  "InADay": "In a day",
  "BestHour": "Best Hour",
  "BestDay": "Best Day",
  "LongestStreak": "Longest Streak",
  "CurrentStreak": "Current Streak",
  "Streak": "Streaks",
  "Day": "Day",
  "Today": "Today",
  "RecentLogs": "Recent Logs",
  "Cancelled": "Cancelled",
  "InProgress": "In Progress",
  "NotStarted": "Not Started",
  "TotalTime": "Total Time",
  "Priority": "Priority",
  "HighPriority": "High",
  "MediumPriority": "Medium",
  "LowPriority": "Low",
  "CurrentProgress": "Current Progress",
  "Minutes": "Minutes",
  "Count": "Count",
  "Save": "Save",
  "DeleteAllData": "Delete All Data",
  "DeleteAllDataWarning": "Are you sure you want to delete all data?",
  "DeleteAllDataSuccess": "All data has been deleted",
  "Yes": "Yes",
  "Hide": "Hide",
  "Show": "Show",
  "storage_permission_required": "Storage permission is required for backup",
  "storage_access_error": "Could not access storage directory",
  "downloads_access_error": "Could not access Downloads directory",
  "backup_created_successfully": "Backup created successfully in Downloads folder",
  "backup_creation_error": "Error creating backup: {}",
  "backup_restored_successfully": "Backup restored successfully",
  "backup_restore_cancelled": "Backup restore cancelled",
  "backup_restore_error": "Error restoring backup: {}",
  "task_completed_title": "🎉 {} Completed",
  "task_completed_desc": "Total duration: {}",
  "item_expired_title": "⚠️ {} Time Expired",
  "item_expired_desc": "Do not exceed the time limit!",
  "notification_permission_required": "Notification permission is required",
  "alarm_permission_required": "Alarm permission is required",
  "notification_channel_name": "Task Completion",
  "notification_channel_desc": "Notifications for completed tasks",
  "ThemeSelection": "Theme Selection",
  "ThemeSelectionSubtitle": "Change Dark/Light theme",
  "DataManagement": "Data Management",
  "DataManagementSubtitle": "Backup or restore your data",
  "ExportData": "Backup Data",
  "ImportData": "Restore from Backup",
  "Subtasks": "Subtasks",
  "AddSubtask": "Add Subtask",
  "EditSubtask": "Edit Subtask",
  "SubtaskEmpty": "Subtask cannot be empty.",
  "HideSubtasks": "Hide subtasks",
  "ShowSubtasks": "Show subtasks",
  "Title": "Title",
  "Description": "Description",
  "EnterTitle": "Enter title",
  "EnterDescription": "Enter description",
  "Location": "Location",
  "EnterLocation": "Enter location",
  "ShowOnMap": "Show on map",
  "AddManualLog": "Add Manual Log",
  "NoLogsYet": "No logs yet",
  "Date": "Date",
  "Time": "Time",
  "Progress": "Progress",
  "EnterCount": "Enter count",
  "Hours": "Hours",
  "CompletedTask": "Completed task",
  "EditLog": "Edit Log",
  "Status": "Status",
  "Category": "Category",
  "Categories": "Categories",
  "CreateCategory": "Create Category",
  "EditCategory": "Edit Category",
  "CategoryName": "Category Name",
  "CategoryNameEmpty": "Category name cannot be empty.",
  "SelectColor": "Select Color",
  "NoCategories": "No categories available",
  "NoCategory": "No Category",
  "CreateNewCategory": "Create New Category",
  "DeleteCategory": "Delete Category",
  "DeleteCategoryConfirmation": "Are you sure you want to delete this category?",
  "NoCategoriesYet": "No categories yet",
  "AddCategory": "Add Category",
  "NoTasksInCategory": "No tasks in this category",
  "Tomorrow": "Tomorrow",
  "Yesterday": "Yesterday",
  "AllTasks": "All Tasks",
  "NoTasksYet": "No tasks yet",
  "Tasks": "Tasks",
  "Close": "Close",
  "ShowCompleted": "Show completed",
  "HideCompleted": "Hide completed",
  "SearchTasks": "Search tasks...",
  "Search": "Search",
  "Filters": "Filters",
  "Copy": "Copy",
  "CopiedDescription": "Description copied to clipboard",
  "ContactUs": "Contact Us",
  "ContactUsSubtitle": "Get in touch with us",
  "PrivacyPolicy": "Privacy Policy",
  "PrivacyPolicySubtitle": "Read our privacy policy"
};
static const Map<String,dynamic> _fr = {
  "Store": "Magasin",
  "Settings": "Paramètres",
  "SelectLanguage": "Sélectionner la langue",
  "Help": "Aide",
  "HelpText": "Conseils sur l'application",
  "HelpDialog": "Avec cette application, vous pouvez créer, modifier et supprimer votre liste de tâches.\n1 heure de travail équivaut à 1 crédit.\nSi les jours de routine sont sélectionnés, cette tâche est enregistrée comme une routine. Si non sélectionné, elle est enregistrée comme une tâche normale.",
  "Exit": "Quitter",
  "Profile": "Profil",
  "Skills": "Compétences",
  "Skill": "Compétence",
  "Attributes": "Attributs",
  "Attribute": "Attribut",
  "CreateSkill": "Créer une compétence",
  "CreateAttribute": "Créer un attribut",
  "WeeklyProgress": "Progrès hebdomadaire",
  "WeeklyWorkHour": "Heures de travail hebdomadaires",
  "Add": "Ajouter",
  "Buy": "Acheter",
  "OnePiece": "{} Pièce",
  "Create": "Créer",
  "Name": "Nom",
  "Cancel": "Annuler",
  "TraitNameEmpty": "Le nom du trait ne peut pas être vide.",
  "RoutineStartDateError": "La date de début de la routine ne peut pas être antérieure à aujourd'hui.",
  "EditTask": "Modifier la tâche",
  "EditRoutine": "Modifier la routine",
  "Edit": "Modifier",
  "AddTask": "Ajouter une tâche",
  "TaskName": "Nom de la tâche",
  "Hour": "Heure",
  "h": "h",
  "Minute": "Minute",
  "m": "m",
  "Second": "Seconde",
  "s": "s",
  "Warning": "Avertissement",
  "Info": "Info",
  "Success": "Succès",
  "NoTaskForToday": "Aucune tâche pour aujourd'hui",
  "RoutineForFuture": "La routine ne peut pas être interagie car elle est dans le futur",
  "Delete": "Supprimer",
  "Failed": "Échoué",
  "ChangeDate": "Changer la date",
  "Times": "Fois",
  "AllTime": "Tout le temps",
  "DaysInProgress": "jours en cours",
  "AvarageDay": "Jour moyen",
  "Routines": "Routines",
  "FutureRoutines": "Routines futures",
  "Completed": "Terminé",
  "NameEmpty": "Le nom ne peut pas être vide.",
  "AddItem": "Ajouter un élément",
  "EditItem": "Modifier l'élément",
  "TaskDescription": "Description de la tâche",
  "SelectTime": "Sélectionner l'heure",
  "Average": "Moyenne",
  "InADay": "En un jour",
  "BestHour": "Meilleure heure",
  "BestDay": "Meilleur jour",
  "LongestStreak": "Plus longue série",
  "CurrentStreak": "Série actuelle",
  "Streak": "Série",
  "Day": "Jour",
  "Today": "Aujourd'hui",
  "RecentLogs": "Journaux récents",
  "Cancelled": "Annulé",
  "InProgress": "En cours",
  "NotStarted": "Pas commencé",
  "TotalTime": "Temps total",
  "Priority": "Priorité",
  "HighPriority": "Haute",
  "MediumPriority": "Moyenne",
  "LowPriority": "Basse",
  "CurrentProgress": "Progrès actuel",
  "Minutes": "Minutes",
  "Count": "Compter",
  "Save": "Enregistrer",
  "DeleteAllData": "Supprimer toutes les données",
  "DeleteAllDataWarning": "Voulez-vous vraiment supprimer toutes les données?",
  "DeleteAllDataSuccess": "Toutes les données ont été supprimées",
  "Yes": "Oui",
  "Hide": "Masquer",
  "Show": "Afficher",
  "storage_permission_required": "L'autorisation de stockage est requise pour la sauvegarde",
  "storage_access_error": "Impossible d'accéder au répertoire de stockage",
  "downloads_access_error": "Impossible d'accéder au répertoire Téléchargements",
  "backup_created_successfully": "Sauvegarde créée avec succès dans le dossier Téléchargements",
  "backup_creation_error": "Erreur lors de la création de la sauvegarde: {}",
  "backup_restored_successfully": "Sauvegarde restaurée avec succès",
  "backup_restore_cancelled": "Restauration de la sauvegarde annulée",
  "backup_restore_error": "Erreur lors de la restauration de la sauvegarde: {}",
  "task_completed_title": "🎉 {} Terminé",
  "task_completed_desc": "Durée totale: {}",
  "item_expired_title": "⚠️ {} Temps expiré",
  "item_expired_desc": "Ne dépassez pas la limite de temps!",
  "notification_permission_required": "L'autorisation de notification est requise",
  "alarm_permission_required": "L'autorisation d'alarme est requise",
  "notification_channel_name": "Achèvement des tâches",
  "notification_channel_desc": "Notifications pour les tâches terminées",
  "ThemeSelection": "Sélection du thème",
  "ThemeSelectionSubtitle": "Changer le thème sombre/clair",
  "DataManagement": "Gestion des données",
  "DataManagementSubtitle": "Sauvegarder ou restaurer vos données",
  "ExportData": "Sauvegarder les données",
  "ImportData": "Restaurer depuis une sauvegarde",
  "Subtasks": "Sous-tâches",
  "AddSubtask": "Ajouter une sous-tâche",
  "EditSubtask": "Modifier une sous-tâche",
  "SubtaskEmpty": "La sous-tâche ne peut pas être vide.",
  "HideSubtasks": "Masquer les sous-tâches",
  "ShowSubtasks": "Afficher les sous-tâches",
  "Location": "Emplacement",
  "EnterLocation": "Entrer l'emplacement",
  "ShowOnMap": "Afficher sur la carte",
  "Title": "Titre",
  "Description": "Description",
  "EnterTitle": "Entrer le titre",
  "EnterDescription": "Entrer la description",
  "AddManualLog": "Ajouter un journal manuel",
  "NoLogsYet": "Pas encore de journaux",
  "Date": "Date",
  "Time": "Heure",
  "Progress": "Progrès",
  "EnterCount": "Entrer le nombre",
  "Hours": "Heures",
  "CompletedTask": "Tâche terminée",
  "EditLog": "Modifier le journal",
  "Status": "Statut",
  "Category": "Catégorie",
  "Categories": "Catégories",
  "CreateCategory": "Créer une catégorie",
  "EditCategory": "Modifier la catégorie",
  "CategoryName": "Nom de la catégorie",
  "CategoryNameEmpty": "Le nom de la catégorie ne peut pas être vide.",
  "SelectColor": "Sélectionner une couleur",
  "NoCategories": "Aucune catégorie disponible",
  "NoCategory": "Pas de catégorie",
  "CreateNewCategory": "Créer une nouvelle catégorie",
  "DeleteCategory": "Supprimer la catégorie",
  "DeleteCategoryConfirmation": "Êtes-vous sûr de vouloir supprimer cette catégorie?",
  "NoCategoriesYet": "Pas encore de catégories",
  "AddCategory": "Ajouter une catégorie",
  "NoTasksInCategory": "Aucune tâche dans cette catégorie",
  "Tomorrow": "Demain",
  "Yesterday": "Hier",
  "AllTasks": "Toutes les tâches",
  "NoTasksYet": "Pas encore de tâches",
  "Tasks": "Tâches",
  "Close": "Fermer",
  "ShowCompleted": "Afficher les tâches terminées",
  "HideCompleted": "Masquer les tâches terminées",
  "SearchTasks": "Rechercher des tâches...",
  "Search": "Rechercher",
  "Filters": "Filtres",
  "Copy": "Copier",
  "CopiedDescription": "Description copiée dans le presse-papiers",
  "ContactUs": "Nous contacter",
  "ContactUsSubtitle": "Entrez en contact avec nous",
  "PrivacyPolicy": "Politique de confidentialité",
  "PrivacyPolicySubtitle": "Lisez notre politique de confidentialité"
};
static const Map<String,dynamic> _ru = {
  "Store": "Магазин",
  "Settings": "Настройки",
  "SelectLanguage": "Выбрать язык",
  "Help": "Помощь",
  "HelpText": "Советы по приложению",
  "HelpDialog": "С помощью этого приложения вы можете создавать, редактировать и удалять свой список дел.\n1 час работы равен 1 кредиту.\nЕсли выбраны дни рутины, эта задача сохраняется как рутина. Если не выбрано, сохраняется как обычная задача.",
  "Exit": "Выход",
  "Profile": "Профиль",
  "Skills": "Навыки",
  "Skill": "Навык",
  "Attributes": "Атрибуты",
  "Attribute": "Атрибут",
  "CreateSkill": "Создать навык",
  "CreateAttribute": "Создать атрибут",
  "WeeklyProgress": "Еженедельный прогресс",
  "WeeklyWorkHour": "Еженедельные рабочие часы",
  "Add": "Добавить",
  "Buy": "Купить",
  "OnePiece": "{} Штука",
  "Create": "Создать",
  "Name": "Имя",
  "Cancel": "Отмена",
  "TraitNameEmpty": "Имя атрибута не может быть пустым.",
  "RoutineStartDateError": "Дата начала рутины не может быть раньше сегодняшнего дня.",
  "EditTask": "Редактировать задачу",
  "EditRoutine": "Редактировать рутину",
  "Edit": "Редактировать",
  "AddTask": "Добавить задачу",
  "TaskName": "Название задачи",
  "Hour": "Час",
  "h": "ч",
  "Minute": "Минута",
  "m": "м",
  "Second": "Секунда",
  "s": "с",
  "Warning": "Предупреждение",
  "Info": "Информация",
  "Success": "Успех",
  "NoTaskForToday": "На сегодня задач нет",
  "RoutineForFuture": "Невозможно взаимодействовать с рутиной, так как она в будущем",
  "Delete": "Удалить",
  "Failed": "Не удалось",
  "ChangeDate": "Изменить дату",
  "Times": "Раз",
  "AllTime": "Все время",
  "DaysInProgress": "дней в процессе",
  "AvarageDay": "Средний день",
  "Routines": "Рутины",
  "FutureRoutines": "Будущие рутины",
  "Completed": "Завершено",
  "NameEmpty": "Имя не может быть пустым.",
  "AddItem": "Добавить элемент",
  "EditItem": "Редактировать элемент",
  "TaskDescription": "Описание задачи",
  "SelectTime": "Выбрать время",
  "Average": "Среднее",
  "InADay": "В день",
  "BestHour": "Лучший час",
  "BestDay": "Лучший день",
  "LongestStreak": "Самая длинная серия",
  "CurrentStreak": "Текущая серия",
  "Streak": "Серия",
  "Day": "День",
  "Today": "Сегодня",
  "RecentLogs": "Последние записи",
  "Cancelled": "Отменено",
  "InProgress": "В процессе",
  "NotStarted": "Не начато",
  "TotalTime": "Общее время",
  "Priority": "Приоритет",
  "HighPriority": "Высокий",
  "MediumPriority": "Средний",
  "LowPriority": "Низкий",
  "CurrentProgress": "Текущий прогресс",
  "Minutes": "Минуты",
  "Count": "Количество",
  "Save": "Сохранить",
  "DeleteAllData": "Удалить все данные",
  "DeleteAllDataWarning": "Вы уверены, что хотите удалить все данные?",
  "DeleteAllDataSuccess": "Все данные были удалены",
  "Yes": "Да",
  "Hide": "Скрыть",
  "Show": "Показать",
  "storage_permission_required": "Для резервного копирования требуется разрешение на хранение",
  "storage_access_error": "Не удалось получить доступ к каталогу хранения",
  "downloads_access_error": "Не удалось получить доступ к каталогу загрузок",
  "backup_created_successfully": "Резервная копия успешно создана в папке Загрузки",
  "backup_creation_error": "Ошибка создания резервной копии: {}",
  "backup_restored_successfully": "Резервная копия успешно восстановлена",
  "backup_restore_cancelled": "Восстановление из резервной копии отменено",
  "backup_restore_error": "Ошибка восстановления из резервной копии: {}",
  "task_completed_title": "🎉 {} Завершено",
  "task_completed_desc": "Общая продолжительность: {}",
  "item_expired_title": "⚠️ {} Время истекло",
  "item_expired_desc": "Не превышайте лимит времени!",
  "notification_permission_required": "Требуется разрешение на уведомления",
  "alarm_permission_required": "Требуется разрешение на будильник",
  "notification_channel_name": "Завершение задачи",
  "notification_channel_desc": "Уведомления о завершенных задачах",
  "ThemeSelection": "Выбор темы",
  "ThemeSelectionSubtitle": "Изменить темную/светлую тему",
  "DataManagement": "Управление данными",
  "DataManagementSubtitle": "Резервное копирование или восстановление данных",
  "ExportData": "Резервное копирование данных",
  "ImportData": "Восстановить из резервной копии",
  "Subtasks": "Подзадачи",
  "AddSubtask": "Добавить подзадачу",
  "EditSubtask": "Редактировать подзадачу",
  "SubtaskEmpty": "Подзадача не может быть пустой.",
  "HideSubtasks": "Скрыть подзадачи",
  "ShowSubtasks": "Показать подзадачи",
  "Title": "Заголовок",
  "Description": "Описание",
  "EnterTitle": "Введите заголовок",
  "EnterDescription": "Введите описание",
  "Location": "Местоположение",
  "EnterLocation": "Введите местоположение",
  "ShowOnMap": "Показать на карте",
  "AddManualLog": "Добавить запись вручную",
  "NoLogsYet": "Пока нет записей",
  "Date": "Дата",
  "Time": "Время",
  "Progress": "Прогресс",
  "EnterCount": "Введите количество",
  "Hours": "Часы",
  "CompletedTask": "Завершенная задача",
  "EditLog": "Редактировать запись",
  "Status": "Статус",
  "Category": "Категория",
  "Categories": "Категории",
  "CreateCategory": "Создать категорию",
  "EditCategory": "Редактировать категорию",
  "CategoryName": "Название категории",
  "CategoryNameEmpty": "Название категории не может быть пустым.",
  "SelectColor": "Выбрать цвет",
  "NoCategories": "Нет доступных категорий",
  "NoCategory": "Без категории",
  "CreateNewCategory": "Создать новую категорию",
  "DeleteCategory": "Удалить категорию",
  "DeleteCategoryConfirmation": "Вы уверены, что хотите удалить эту категорию?",
  "NoCategoriesYet": "Пока нет категорий",
  "AddCategory": "Добавить категорию",
  "NoTasksInCategory": "В этой категории нет задач",
  "Tomorrow": "Завтра",
  "Yesterday": "Вчера",
  "AllTasks": "Все задачи",
  "NoTasksYet": "Пока нет задач",
  "Tasks": "Задачи",
  "Close": "Закрыть",
  "ShowCompleted": "Показать завершенные",
  "HideCompleted": "Скрыть завершенные",
  "SearchTasks": "Поиск задач...",
  "Search": "Поиск",
  "Filters": "Фильтры",
  "Copy": "Копировать",
  "CopiedDescription": "Описание скопировано в буфер обмена",
  "ContactUs": "Связаться с нами",
  "ContactUsSubtitle": "Свяжитесь с нами",
  "PrivacyPolicy": "Политика конфиденциальности",
  "PrivacyPolicySubtitle": "Ознакомьтесь с нашей политикой конфиденциальности"
};
static const Map<String,dynamic> _tr = {
  "Store": "Mağaza",
  "Settings": "Ayarlar",
  "SelectLanguage": "Dil Seçimi",
  "Help": "Yardım",
  "HelpText": "Uygulama hakkında ipuçları.",
  "HelpDialog": "Bu uygulama ile yapılacaklar listenizi oluşturabilir, düzenleyebilir ve silebilirsiniz.\n1 saat çalışma 1 krediye denk gelmektedir.\nrutin günleri seçilirse o task rutin olarak kaydedilir. Eğer seçilmezse normal task olarak kaydedilir.",
  "Exit": "Çıkış",
  "Profile": "Profil",
  "Skills": "Yetenekler",
  "Skill": "Yetenek",
  "Attributes": "Özellikler",
  "Attribute": "Özellik",
  "CreateSkill": "Yetenek Oluştur",
  "CreateAttribute": "Özellik Oluştur",
  "WeeklyProgress": "Haftalık İlerleme",
  "WeeklyWorkHour": "Haftalık Çalışma Saati",
  "Add": "Ekle",
  "Buy": "Satın Al",
  "OnePiece": "{} Adet",
  "Create": "Oluştur",
  "Name": "İsim",
  "Cancel": "İptal",
  "TraitNameEmpty": "Beceri adı boş olamaz.",
  "RoutineStartDateError": "Rutin başlangıç tarihi bugünden önce olamaz.",
  "EditTask": "Görevi Düzenle",
  "EditRoutine": "Rutini Düzenle",
  "Edit": "Düzenle",
  "AddTask": "Görev Ekle",
  "TaskName": "Görev Adı",
  "Hour": "Saat",
  "h": "s",
  "Minute": "Dakika",
  "m": "d",
  "Second": "Saniye",
  "s": "s",
  "Warning": "Uyarı",
  "Info": "Bilgi",
  "Success": "Başarılı",
  "NoTaskForToday": "Bugün için görev yok",
  "RoutineForFuture": "Rutin gelecekte olduğu için etkileşimde bulunulamaz",
  "Delete": "Sil",
  "Failed": "Başarısız",
  "ChangeDate": "Tarihi Değiştir",
  "Times": "Kez",
  "AllTime": "Tüm Zamanlar",
  "DaysInProgress": "gündür devam ediyor",
  "AvarageDay": "Günde ortalama",
  "Routines": "Rutinler",
  "FutureRoutines": "Gelecek Rutinler",
  "Completed": "Tamamlandı",
  "NameEmpty": "İsim boş bırakılamaz.",
  "AddItem": "Ürün Ekle",
  "EditItem": "Ürünü Düzenle",
  "TaskDescription": "Görev Açıklaması",
  "SelectTime": "Saat Seç",
  "Average": "Ortalama",
  "InADay": "Günde",
  "BestHour": "En İyi Saat",
  "BestDay": "En İyi Gün",
  "LongestStreak": "En Uzun Süreklilik",
  "CurrentStreak": "Mevcut Süreklilik",
  "Streak": "Süreklilik",
  "Day": "Gün",
  "Today": "Bugün",
  "RecentLogs": "Son Kayıtlar",
  "Cancelled": "İptal Edildi",
  "InProgress": "Devam Ediyor",
  "NotStarted": "Başlamadı",
  "TotalTime": "Toplam Süre",
  "Priority": "Öncelik",
  "HighPriority": "Yüksek",
  "MediumPriority": "Orta",
  "LowPriority": "Düşük",
  "CurrentProgress": "Mevcut İlerleme",
  "Minutes": "Dakika",
  "Count": "Adet",
  "Save": "Kaydet",
  "DeleteAllData": "Tüm Verileri Sil",
  "DeleteAllDataWarning": "Tüm verileri silmek istediğinizden emin misiniz?",
  "DeleteAllDataSuccess": "Tüm veriler silindi.",
  "Yes": "Evet",
  "Hide": "Gizle",
  "Show": "Göster",
  "storage_permission_required": "Yedekleme için depolama izni gerekli",
  "storage_access_error": "Depolama dizinine erişilemedi",
  "downloads_access_error": "İndirilenler klasörüne erişilemedi",
  "backup_created_successfully": "Yedekleme İndirilenler klasörüne başarıyla kaydedildi",
  "backup_creation_error": "Yedekleme oluşturulurken hata: {}",
  "backup_restored_successfully": "Veriler başarıyla geri yüklendi",
  "backup_restore_cancelled": "Veriler geri yükleme iptal edildi",
  "backup_restore_error": "Veriler geri yüklenirken hata: {}",
  "task_completed_title": "🎉 {} Tamamlandı",
  "task_completed_desc": "Toplam süre: {}",
  "item_expired_title": "⚠️ {} Süresi Doldu",
  "item_expired_desc": "Süre sınırını aşmayın!",
  "notification_permission_required": "Bildirim izni gerekli",
  "alarm_permission_required": "Alarm izni gerekli",
  "notification_channel_name": "Görev Tamamlama",
  "notification_channel_desc": "Tamamlanan görevler için bildirimler",
  "ThemeSelection": "Tema Seçimi",
  "ThemeSelectionSubtitle": "Koyu/Açık temayı değiştirin",
  "DataManagement": "Veri Yönetimi",
  "DataManagementSubtitle": "Verilerinizi yedekleyin veya geri yükleyin",
  "ExportData": "Verileri Yedekle",
  "ImportData": "Yedekten Geri Yükle",
  "Subtasks": "Alt Görevler",
  "AddSubtask": "Alt Görev Ekle",
  "EditSubtask": "Alt Görev Düzenle",
  "SubtaskEmpty": "Alt görev boş olamaz.",
  "HideSubtasks": "Alt görevleri gizle",
  "ShowSubtasks": "Alt görevleri göster",
  "Title": "Başlık",
  "Description": "Açıklama",
  "EnterTitle": "Başlık girin",
  "EnterDescription": "Açıklama girin",
  "Location": "Konum",
  "EnterLocation": "Konum gir",
  "ShowOnMap": "Haritada göster",
  "AddManualLog": "Manuel Kayıt Ekle",
  "NoLogsYet": "Henüz kayıt yok",
  "Date": "Tarih",
  "Time": "Saat",
  "Progress": "İlerleme",
  "EnterCount": "Sayı girin",
  "Hours": "Saat",
  "CompletedTask": "Tamamlanan görev",
  "EditLog": "Kaydı Düzenle",
  "Status": "Durum",
  "Category": "Kategori",
  "Categories": "Kategoriler",
  "CreateCategory": "Kategori Oluştur",
  "EditCategory": "Kategori Düzenle",
  "CategoryName": "Kategori Adı",
  "CategoryNameEmpty": "Kategori adı boş olamaz.",
  "SelectColor": "Renk Seç",
  "NoCategories": "Kategori bulunamadı",
  "NoCategory": "Kategori Yok",
  "CreateNewCategory": "Yeni Kategori Oluştur",
  "DeleteCategory": "Kategoriyi Sil",
  "DeleteCategoryConfirmation": "Bu kategoriyi silmek istediğinizden emin misiniz?",
  "NoCategoriesYet": "Henüz kategori yok",
  "AddCategory": "Kategori Ekle",
  "NoTasksInCategory": "Bu kategoride görev yok",
  "Tomorrow": "Yarın",
  "Yesterday": "Dün",
  "AllTasks": "Tüm Görevler",
  "NoTasksYet": "Henüz görev yok",
  "Tasks": "Görevler",
  "Close": "Kapat",
  "ShowCompleted": "Tamamlananları göster",
  "HideCompleted": "Tamamlananları gizle",
  "SearchTasks": "Görevleri Ara",
  "Search": "Ara",
  "Filters": "Filtreler",
  "Copy": "Kopyala",
  "CopiedDescription": "Açıklama panoya kopyalandı",
  "ContactUs": "Bize Ulaşın",
  "ContactUsSubtitle": "Bizimle iletişime geçin",
  "PrivacyPolicy": "Gizlilik Politikası",
  "PrivacyPolicySubtitle": "Gizlilik politikamızı okuyun"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"de": _de, "en": _en, "fr": _fr, "ru": _ru, "tr": _tr};
}
