// Mocks generated by Mockito 5.4.4 from annotations
// in next_level/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i16;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:next_level/Enum/task_status_enum.dart' as _i23;
import 'package:next_level/Model/category_model.dart' as _i10;
import 'package:next_level/Model/daily_streak_model.dart' as _i12;
import 'package:next_level/Model/routine_model.dart' as _i8;
import 'package:next_level/Model/store_item_model.dart' as _i6;
import 'package:next_level/Model/subtask_model.dart' as _i17;
import 'package:next_level/Model/task_log_model.dart' as _i11;
import 'package:next_level/Model/task_model.dart' as _i9;
import 'package:next_level/Model/trait_model.dart' as _i7;
import 'package:next_level/Model/user_model.dart' as _i5;
import 'package:next_level/Provider/task_log_provider.dart' as _i21;
import 'package:next_level/Provider/task_provider.dart' as _i2;
import 'package:next_level/Repository/category_repository.dart' as _i19;
import 'package:next_level/Repository/routine_repository.dart' as _i14;
import 'package:next_level/Repository/task_log_repository.dart' as _i22;
import 'package:next_level/Repository/task_repository.dart' as _i13;
import 'package:next_level/Service/hive_service.dart' as _i3;
import 'package:next_level/Service/home_widget_helper.dart' as _i18;
import 'package:next_level/Service/undo_service.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskProvider_0 extends _i1.SmartFake implements _i2.TaskProvider {
  _FakeTaskProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i3.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> addUser(_i5.UserModel? userModel) => (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [userModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserModel?> getUser(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i4.Future<_i5.UserModel?>.value(),
      ) as _i4.Future<_i5.UserModel?>);

  @override
  _i4.Future<void> updateUser(_i5.UserModel? userModel) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [userModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.UserModel>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);

  @override
  _i4.Future<void> addItem(_i6.ItemModel? itemModel) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [itemModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.ItemModel>> getItems() => (super.noSuchMethod(
        Invocation.method(
          #getItems,
          [],
        ),
        returnValue: _i4.Future<List<_i6.ItemModel>>.value(<_i6.ItemModel>[]),
      ) as _i4.Future<List<_i6.ItemModel>>);

  @override
  _i4.Future<void> updateItem(_i6.ItemModel? itemModel) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [itemModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteItem(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTrait(_i7.TraitModel? traitModel) => (super.noSuchMethod(
        Invocation.method(
          #addTrait,
          [traitModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.TraitModel>> getTraits() => (super.noSuchMethod(
        Invocation.method(
          #getTraits,
          [],
        ),
        returnValue: _i4.Future<List<_i7.TraitModel>>.value(<_i7.TraitModel>[]),
      ) as _i4.Future<List<_i7.TraitModel>>);

  @override
  _i4.Future<void> updateTrait(_i7.TraitModel? traitModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrait,
          [traitModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTrait(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrait,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRoutine(_i8.RoutineModel? routineModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRoutine,
          [routineModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.RoutineModel>> getRoutines() => (super.noSuchMethod(
        Invocation.method(
          #getRoutines,
          [],
        ),
        returnValue:
            _i4.Future<List<_i8.RoutineModel>>.value(<_i8.RoutineModel>[]),
      ) as _i4.Future<List<_i8.RoutineModel>>);

  @override
  _i4.Future<void> updateRoutine(_i8.RoutineModel? routineModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoutine,
          [routineModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoutine(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoutine,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTask(_i9.TaskModel? taskModel) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [taskModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.TaskModel>> getTasks() => (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i9.TaskModel>>.value(<_i9.TaskModel>[]),
      ) as _i4.Future<List<_i9.TaskModel>>);

  @override
  _i4.Future<void> updateTask(_i9.TaskModel? taskModel) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [taskModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addCategory(_i10.CategoryModel? categoryModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [categoryModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i10.CategoryModel>>.value(<_i10.CategoryModel>[]),
      ) as _i4.Future<List<_i10.CategoryModel>>);

  @override
  _i4.Future<void> updateCategory(_i10.CategoryModel? categoryModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [categoryModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCategoryBox() => (super.noSuchMethod(
        Invocation.method(
          #clearCategoryBox,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTaskLog(_i11.TaskLogModel? taskLogModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTaskLog,
          [taskLogModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.TaskLogModel>> getTaskLogs() => (super.noSuchMethod(
        Invocation.method(
          #getTaskLogs,
          [],
        ),
        returnValue:
            _i4.Future<List<_i11.TaskLogModel>>.value(<_i11.TaskLogModel>[]),
      ) as _i4.Future<List<_i11.TaskLogModel>>);

  @override
  _i4.Future<List<_i11.TaskLogModel>> getTaskLogsByTaskId(int? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskLogsByTaskId,
          [taskId],
        ),
        returnValue:
            _i4.Future<List<_i11.TaskLogModel>>.value(<_i11.TaskLogModel>[]),
      ) as _i4.Future<List<_i11.TaskLogModel>>);

  @override
  _i4.Future<List<_i11.TaskLogModel>> getTaskLogsByRoutineId(int? routineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskLogsByRoutineId,
          [routineId],
        ),
        returnValue:
            _i4.Future<List<_i11.TaskLogModel>>.value(<_i11.TaskLogModel>[]),
      ) as _i4.Future<List<_i11.TaskLogModel>>);

  @override
  _i4.Future<void> deleteTaskLog(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTaskLog,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addDailyStreak(_i12.DailyStreakModel? streakModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDailyStreak,
          [streakModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i12.DailyStreakModel?> getDailyStreak(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyStreak,
          [date],
        ),
        returnValue: _i4.Future<_i12.DailyStreakModel?>.value(),
      ) as _i4.Future<_i12.DailyStreakModel?>);

  @override
  _i4.Future<List<_i12.DailyStreakModel>> getAllDailyStreaks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDailyStreaks,
          [],
        ),
        returnValue: _i4.Future<List<_i12.DailyStreakModel>>.value(
            <_i12.DailyStreakModel>[]),
      ) as _i4.Future<List<_i12.DailyStreakModel>>);

  @override
  _i4.Future<void> clearDailyStreakBox() => (super.noSuchMethod(
        Invocation.method(
          #clearDailyStreakBox,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createTasksFromRoutines() => (super.noSuchMethod(
        Invocation.method(
          #createTasksFromRoutines,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllData({
    bool? isLogout = false,
    bool? isImport = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
          {
            #isLogout: isLogout,
            #isImport: isImport,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> exportData() => (super.noSuchMethod(
        Invocation.method(
          #exportData,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> importData() => (super.noSuchMethod(
        Invocation.method(
          #importData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> resetAllRoutineProgress() => (super.noSuchMethod(
        Invocation.method(
          #resetAllRoutineProgress,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i13.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setHiveService(_i3.HiveService? service) => super.noSuchMethod(
        Invocation.method(
          #setHiveService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i9.TaskModel>> getTasks() => (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i9.TaskModel>>.value(<_i9.TaskModel>[]),
      ) as _i4.Future<List<_i9.TaskModel>>);

  @override
  _i4.Future<int> addTask(_i9.TaskModel? taskModel) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [taskModel],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateTask(_i9.TaskModel? taskModel) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [taskModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [RoutineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineRepository extends _i1.Mock implements _i14.RoutineRepository {
  MockRoutineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setHiveService(_i3.HiveService? service) => super.noSuchMethod(
        Invocation.method(
          #setHiveService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i8.RoutineModel>> getRoutines() => (super.noSuchMethod(
        Invocation.method(
          #getRoutines,
          [],
        ),
        returnValue:
            _i4.Future<List<_i8.RoutineModel>>.value(<_i8.RoutineModel>[]),
      ) as _i4.Future<List<_i8.RoutineModel>>);

  @override
  _i4.Future<int> addRoutine(_i8.RoutineModel? routineModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRoutine,
          [routineModel],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateRoutine(_i8.RoutineModel? routineModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoutine,
          [routineModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoutine(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoutine,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UndoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUndoService extends _i1.Mock implements _i15.UndoService {
  MockUndoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void cancelUndoTimer(String? key) => super.noSuchMethod(
        Invocation.method(
          #cancelUndoTimer,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerDeleteTask(
    _i9.TaskModel? task, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerDeleteTask,
          [task],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.TaskModel? undoDeleteTask(int? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #undoDeleteTask,
        [taskId],
      )) as _i9.TaskModel?);

  @override
  void registerDeleteRoutine(
    _i8.RoutineModel? routine, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerDeleteRoutine,
          [routine],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.RoutineModel? undoDeleteRoutine(int? routineId) =>
      (super.noSuchMethod(Invocation.method(
        #undoDeleteRoutine,
        [routineId],
      )) as _i8.RoutineModel?);

  @override
  void registerDeleteSubtask(
    int? taskId,
    _i17.SubTaskModel? subtask, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerDeleteSubtask,
          [
            taskId,
            subtask,
          ],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i17.SubTaskModel? undoDeleteSubtask(
    int? taskId,
    int? subtaskId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #undoDeleteSubtask,
        [
          taskId,
          subtaskId,
        ],
      )) as _i17.SubTaskModel?);

  @override
  void registerDateChange(
    int? taskId,
    _i15.TaskDateChangeData? data, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerDateChange,
          [
            taskId,
            data,
          ],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.TaskDateChangeData? undoDateChange(int? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #undoDateChange,
        [taskId],
      )) as _i15.TaskDateChangeData?);

  @override
  void registerCompletion(
    int? taskId,
    _i15.TaskCompletionData? data, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCompletion,
          [
            taskId,
            data,
          ],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.TaskCompletionData? undoCompletion(int? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #undoCompletion,
        [taskId],
      )) as _i15.TaskCompletionData?);

  @override
  void registerCancellation(
    int? taskId,
    _i15.TaskCancellationData? data, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCancellation,
          [
            taskId,
            data,
          ],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.TaskCancellationData? undoCancellation(int? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #undoCancellation,
        [taskId],
      )) as _i15.TaskCancellationData?);

  @override
  void registerFailure(
    int? taskId,
    _i15.TaskFailureData? data, {
    _i16.VoidCallback? onExpire,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerFailure,
          [
            taskId,
            data,
          ],
          {#onExpire: onExpire},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.TaskFailureData? undoFailure(int? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #undoFailure,
        [taskId],
      )) as _i15.TaskFailureData?);
}

/// A class which mocks [HomeWidgetHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeWidgetHelper extends _i1.Mock implements _i18.HomeWidgetHelper {
  MockHomeWidgetHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateAllWidgets() => (super.noSuchMethod(
        Invocation.method(
          #updateAllWidgets,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i19.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i10.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i10.CategoryModel>>.value(<_i10.CategoryModel>[]),
      ) as _i4.Future<List<_i10.CategoryModel>>);

  @override
  _i4.Future<String> addCategory(_i10.CategoryModel? categoryModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [categoryModel],
        ),
        returnValue: _i4.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #addCategory,
            [categoryModel],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateCategory(_i10.CategoryModel? categoryModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [categoryModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TaskLogProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLogProvider extends _i1.Mock implements _i21.TaskLogProvider {
  MockTaskLogProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.TaskLogModel> get taskLogList => (super.noSuchMethod(
        Invocation.getter(#taskLogList),
        returnValue: <_i11.TaskLogModel>[],
      ) as List<_i11.TaskLogModel>);

  @override
  set taskLogList(List<_i11.TaskLogModel>? _taskLogList) => super.noSuchMethod(
        Invocation.setter(
          #taskLogList,
          _taskLogList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TaskProvider get taskProvider => (super.noSuchMethod(
        Invocation.getter(#taskProvider),
        returnValue: _FakeTaskProvider_0(
          this,
          Invocation.getter(#taskProvider),
        ),
      ) as _i2.TaskProvider);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setRepository(_i22.TaskLogRepository? repo) => super.noSuchMethod(
        Invocation.method(
          #setRepository,
          [repo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTaskRepository(_i13.TaskRepository? repo) => super.noSuchMethod(
        Invocation.method(
          #setTaskRepository,
          [repo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTaskProvider(_i2.TaskProvider? provider) => super.noSuchMethod(
        Invocation.method(
          #setTaskProvider,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> loadTaskLogs() => (super.noSuchMethod(
        Invocation.method(
          #loadTaskLogs,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTaskLog(
    _i9.TaskModel? taskModel, {
    DateTime? customLogDate,
    Duration? customDuration,
    int? customCount,
    _i23.TaskStatusEnum? customStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTaskLog,
          [taskModel],
          {
            #customLogDate: customLogDate,
            #customDuration: customDuration,
            #customCount: customCount,
            #customStatus: customStatus,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i11.TaskLogModel> getLogsByTaskId(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #getLogsByTaskId,
          [taskId],
        ),
        returnValue: <_i11.TaskLogModel>[],
      ) as List<_i11.TaskLogModel>);

  @override
  List<_i11.TaskLogModel> getLogsByRoutineId(int? routineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogsByRoutineId,
          [routineId],
        ),
        returnValue: <_i11.TaskLogModel>[],
      ) as List<_i11.TaskLogModel>);

  @override
  List<_i11.TaskLogModel> getRecentLogs(int? count) => (super.noSuchMethod(
        Invocation.method(
          #getRecentLogs,
          [count],
        ),
        returnValue: <_i11.TaskLogModel>[],
      ) as List<_i11.TaskLogModel>);

  @override
  _i4.Future<void> deleteLogsByTaskId(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLogsByTaskId,
          [taskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLogsByRoutineId(int? routineId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLogsByRoutineId,
          [routineId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllLogs() => (super.noSuchMethod(
        Invocation.method(
          #clearAllLogs,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLogByTaskIdAndStatus(
    int? taskId,
    _i23.TaskStatusEnum? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLogByTaskIdAndStatus,
          [
            taskId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTaskLog(int? logId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTaskLog,
          [logId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> editTaskLog(
    int? logId,
    dynamic newValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTaskLog,
          [
            logId,
            newValue,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCounterTaskLogStatuses(_i9.TaskModel? updatedTask) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCounterTaskLogStatuses,
          [updatedTask],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTimerTaskLogStatuses(_i9.TaskModel? updatedTask) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTimerTaskLogStatuses,
          [updatedTask],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recalculateTaskProgress(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #recalculateTaskProgress,
          [taskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TaskLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLogRepository extends _i1.Mock implements _i22.TaskLogRepository {
  MockTaskLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i11.TaskLogModel>> getTaskLogs() => (super.noSuchMethod(
        Invocation.method(
          #getTaskLogs,
          [],
        ),
        returnValue:
            _i4.Future<List<_i11.TaskLogModel>>.value(<_i11.TaskLogModel>[]),
      ) as _i4.Future<List<_i11.TaskLogModel>>);

  @override
  _i4.Future<int> addTaskLog(_i11.TaskLogModel? taskLog) => (super.noSuchMethod(
        Invocation.method(
          #addTaskLog,
          [taskLog],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateTaskLog(_i11.TaskLogModel? taskLog) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskLog,
          [taskLog],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTaskLog(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTaskLog,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> generateNextId() => (super.noSuchMethod(
        Invocation.method(
          #generateNextId,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [TaskProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskProvider extends _i1.Mock implements _i2.TaskProvider {
  MockTaskProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.RoutineModel> get routineList => (super.noSuchMethod(
        Invocation.getter(#routineList),
        returnValue: <_i8.RoutineModel>[],
      ) as List<_i8.RoutineModel>);

  @override
  set routineList(List<_i8.RoutineModel>? _routineList) => super.noSuchMethod(
        Invocation.setter(
          #routineList,
          _routineList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i9.TaskModel> get taskList => (super.noSuchMethod(
        Invocation.getter(#taskList),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  set taskList(List<_i9.TaskModel>? _taskList) => super.noSuchMethod(
        Invocation.setter(
          #taskList,
          _taskList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  DateTime get selectedDate => (super.noSuchMethod(
        Invocation.getter(#selectedDate),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#selectedDate),
        ),
      ) as DateTime);

  @override
  set selectedDate(DateTime? _selectedDate) => super.noSuchMethod(
        Invocation.setter(
          #selectedDate,
          _selectedDate,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get showCompleted => (super.noSuchMethod(
        Invocation.getter(#showCompleted),
        returnValue: false,
      ) as bool);

  @override
  set showCompleted(bool? _showCompleted) => super.noSuchMethod(
        Invocation.setter(
          #showCompleted,
          _showCompleted,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get showArchived => (super.noSuchMethod(
        Invocation.getter(#showArchived),
        returnValue: false,
      ) as bool);

  @override
  set showArchived(bool? _showArchived) => super.noSuchMethod(
        Invocation.setter(
          #showArchived,
          _showArchived,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedCategoryId(String? _selectedCategoryId) => super.noSuchMethod(
        Invocation.setter(
          #selectedCategoryId,
          _selectedCategoryId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setTaskRepository(_i13.TaskRepository? repo) => super.noSuchMethod(
        Invocation.method(
          #setTaskRepository,
          [repo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRoutineRepository(_i14.RoutineRepository? repo) => super.noSuchMethod(
        Invocation.method(
          #setRoutineRepository,
          [repo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUndoService(_i15.UndoService? service) => super.noSuchMethod(
        Invocation.method(
          #setUndoService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHomeWidgetHelper(_i18.HomeWidgetHelper? helper) => super.noSuchMethod(
        Invocation.method(
          #setHomeWidgetHelper,
          [helper],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCategoryRepository(_i19.CategoryRepository? repo) =>
      super.noSuchMethod(
        Invocation.method(
          #setCategoryRepository,
          [repo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTaskLogProvider(_i21.TaskLogProvider? provider) => super.noSuchMethod(
        Invocation.method(
          #setTaskLogProvider,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> loadCategories() => (super.noSuchMethod(
        Invocation.method(
          #loadCategories,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadShowCompletedState() => (super.noSuchMethod(
        Invocation.method(
          #loadShowCompletedState,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRoutineVacationStatus(
    int? routineId,
    bool? isActiveOnVacationDays,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoutineVacationStatus,
          [
            routineId,
            isActiveOnVacationDays,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTask(_i9.TaskModel? taskModel) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [taskModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> addRoutine(_i8.RoutineModel? routineModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRoutine,
          [routineModel],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<void> editTask({
    required _i9.TaskModel? taskModel,
    required List<int>? selectedDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTask,
          [],
          {
            #taskModel: taskModel,
            #selectedDays: selectedDays,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void updateItems() => super.noSuchMethod(
        Invocation.method(
          #updateItems,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeSelectedDate(DateTime? selectedDateZ) => super.noSuchMethod(
        Invocation.method(
          #changeSelectedDate,
          [selectedDateZ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateTaskDate({
    required _i9.TaskModel? taskModel,
    required DateTime? selectedDate,
    bool? showUndo = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskDate,
          [],
          {
            #taskModel: taskModel,
            #selectedDate: selectedDate,
            #showUndo: showUndo,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void changeTaskDateWithoutDialog({
    required _i9.TaskModel? taskModel,
    required DateTime? newDate,
    bool? showUndo = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #changeTaskDateWithoutDialog,
          [],
          {
            #taskModel: taskModel,
            #newDate: newDate,
            #showUndo: showUndo,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void checkTaskStatusForNotifications(_i9.TaskModel? taskModel) =>
      super.noSuchMethod(
        Invocation.method(
          #checkTaskStatusForNotifications,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void checkNotification(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #checkNotification,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancelTask(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #cancelTask,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void failedTask(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #failedTask,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> skipRoutinesForDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #skipRoutinesForDate,
          [date],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(int? taskID) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskID],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoutine(int? routineID) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoutine,
          [routineID],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void completeRoutine(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #completeRoutine,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> changeShowCompleted() => (super.noSuchMethod(
        Invocation.method(
          #changeShowCompleted,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkDailyDPBonuses(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #checkDailyDPBonuses,
          [date],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSelectedCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSelectedCategory,
          [categoryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleShowArchived() => (super.noSuchMethod(
        Invocation.method(
          #toggleShowArchived,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleTaskSubtaskVisibility(_i9.TaskModel? taskModel) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleTaskSubtaskVisibility,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addSubtask(
    _i9.TaskModel? taskModel,
    String? subtaskTitle, [
    String? description,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addSubtask,
          [
            taskModel,
            subtaskTitle,
            description,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeSubtask(
    _i9.TaskModel? taskModel,
    _i17.SubTaskModel? subtask, {
    bool? showUndo = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeSubtask,
          [
            taskModel,
            subtask,
          ],
          {#showUndo: showUndo},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSubtasks(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #clearSubtasks,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSubtaskCompletion(
    _i9.TaskModel? taskModel,
    _i17.SubTaskModel? subtask, {
    bool? showUndo = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleSubtaskCompletion,
          [
            taskModel,
            subtask,
          ],
          {#showUndo: showUndo},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSubtask(
    _i9.TaskModel? taskModel,
    _i17.SubTaskModel? subtask,
    String? title,
    String? description,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSubtask,
          [
            taskModel,
            subtask,
            title,
            description,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sortTasksByPriorityAndTime(List<_i9.TaskModel>? tasks) =>
      super.noSuchMethod(
        Invocation.method(
          #sortTasksByPriorityAndTime,
          [tasks],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i9.TaskModel> getTasksForDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getTasksForDate,
          [date],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  List<_i9.TaskModel> getPinnedTasksForToday() => (super.noSuchMethod(
        Invocation.method(
          #getPinnedTasksForToday,
          [],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  _i4.Future<void> toggleTaskPin(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #toggleTaskPin,
          [taskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> reorderTasks({
    required int? oldIndex,
    required int? newIndex,
    required bool? isPinnedList,
    required bool? isRoutineList,
    required bool? isOverdueList,
    bool? isGhostRoutineList = false,
    List<_i9.TaskModel>? explicitList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderTasks,
          [],
          {
            #oldIndex: oldIndex,
            #newIndex: newIndex,
            #isPinnedList: isPinnedList,
            #isRoutineList: isRoutineList,
            #isOverdueList: isOverdueList,
            #isGhostRoutineList: isGhostRoutineList,
            #explicitList: explicitList,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  List<_i9.TaskModel> getRoutineTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoutineTasksForDate,
          [date],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  List<_i9.TaskModel> getGhostRoutineTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGhostRoutineTasksForDate,
          [date],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  List<_i9.TaskModel> getTasksByCategoryId(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByCategoryId,
          [categoryId],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  List<_i9.TaskModel> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  void completeTaskWithUndo(
    _i9.TaskModel? taskModel, {
    bool? showUndo = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #completeTaskWithUndo,
          [taskModel],
          {#showUndo: showUndo},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> unarchiveRoutine(int? routineID) => (super.noSuchMethod(
        Invocation.method(
          #unarchiveRoutine,
          [routineID],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i9.TaskModel> getOverdueTasks() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueTasks,
          [],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  List<_i8.RoutineModel> getArchivedRoutines() => (super.noSuchMethod(
        Invocation.method(
          #getArchivedRoutines,
          [],
        ),
        returnValue: <_i8.RoutineModel>[],
      ) as List<_i8.RoutineModel>);

  @override
  List<_i9.TaskModel> getArchivedTasks() => (super.noSuchMethod(
        Invocation.method(
          #getArchivedTasks,
          [],
        ),
        returnValue: <_i9.TaskModel>[],
      ) as List<_i9.TaskModel>);

  @override
  void showTaskFailureUndo(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #showTaskFailureUndo,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskFailureUndoWithPreviousStatus(
    _i9.TaskModel? taskModel,
    _i23.TaskStatusEnum? previousStatus,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showTaskFailureUndoWithPreviousStatus,
          [
            taskModel,
            previousStatus,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskCancellationUndo(_i9.TaskModel? taskModel) => super.noSuchMethod(
        Invocation.method(
          #showTaskCancellationUndo,
          [taskModel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskCancellationUndoWithPreviousStatus(
    _i9.TaskModel? taskModel,
    _i23.TaskStatusEnum? previousStatus,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showTaskCancellationUndoWithPreviousStatus,
          [
            taskModel,
            previousStatus,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> unarchiveTask(_i9.TaskModel? taskModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #unarchiveTask,
          [taskModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
